; red_bank_s3
[env:red_bank_s3]
extends = esp32s3_base
board = red_bank_s3
board_check = true
upload_protocol = esptool
monitor_speed = 115200
board_build.partitions = partition-table.csv

build_flags = ${esp32s3_base.build_flags} 
  -DRED_BANK_S3
  -DUSE_EINK
  -DEINK_DISPLAY_MODEL=GxEPD2_270_GDEY027T91
  ; -DEINK_DISPLAY_MODEL=GxEPD2_270
  -DEINK_WIDTH=264
  -DEINK_HEIGHT=176
  -DUSE_EINK_DYNAMICDISPLAY            ; Enable Dynamic EInk
  -DEINK_LIMIT_FASTREFRESH=20          ; How many consecutive fast-refreshes are permitted
  -DPRIVATE_HW                       
  -Ivariants/esp32s3/red_bank_s3
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -DEINK_BACKGROUND_USES_FAST          ; (Optional) Use FAST refresh for both BACKGROUND and RESPONSIVE, until a limit is reached.
  -DCNFONT_EMBED_INTERNAL_TABLE=1
lib_deps =
  ${esp32s3_base.lib_deps}
  ; https://github.com/meshtastic/GxEPD2/archive/b202ebfec6a4821e098cf7a625ba0f6f2400292d.zip
  https://github.com/ZinggJM/GxEPD2/archive/refs/heads/master.zip
